### ISSUE TITLE
请问PsychoFlickr数据集的性格标签在哪里下载

### ISSUE THREAD

**Issue by WeitaoVan** [zhuhancheng/PA_IAA_#1]
您好，感谢分享。

网上可以下载到PsychoFlickr的所有图片，但是无法知道每张图片对应的personality是什么，请问如何知道这一信息呢？谢谢

**Comment by 159W** [comment]
您好，请问可以提供PsychoFlickr数据集的下载地址吗，在网上没有找到

**Comment by tianyiwen** [comment]
您好，PsychoFlickr的图片标签您找到了吗，可以告知如何找到personality标签吗？

**Comment by BohanLi0110** [comment]
> 您好，感谢分享。
> 
> 网上可以下载到PsychoFlickr的所有图片，但是无法知道每张图片对应的personality是什么，请问如何知道这一信息呢？谢谢

请问您方便提供一下PsychoFlickr数据集的链接吗？或者资源？目前链接失效了。谢谢！
